### ISSUE TITLE
litellm.APIConnectionError: encoding with 'idna' codec failed (UnicodeError: label empty or too long)

### ISSUE THREAD

**Issue by danielorozco06** [tw-haiven/haiven#485]
Hi,

we are presenting the next error when send a chat request after execute "quickest-way-to-try-it-out":

![image](https://github.com/user-attachments/assets/eca8cada-338a-47a6-ad61-83674f0d5588)

`litellm.APIConnectionError: encoding with 'idna' codec failed (UnicodeError: label empty or too long) Traceback (most recent call last): File "/usr/local/lib/python3.11/site-packages/litellm/main.py", line 2564, in completion response = bedrock_converse_chat_completion.completion( ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/site-packages/litellm/llms/bedrock/chat/converse_handler.py", line 388, in completion completion_stream = make_sync_call( ^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/site-packages/litellm/llms/bedrock/chat/converse_handler.py", line 59, in make_sync_call response = client.post( ^^^^^^^^^^^^ File "/usr/local/lib/python3.11/site-packages/litellm/llms/custom_httpx/http_handler.py", line 388, in post raise e File "/usr/local/lib/python3.11/site-packages/litellm/llms/custom_httpx/http_handler.py", line 371, in post response = self.client.send(req, stream=stream) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/site-packages/httpx/_client.py", line 926, in send response = self._send_handling_auth( ^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/site-packages/httpx/_client.py", line 954, in _send_handling_auth response = self._send_handling_redirects( ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/site-packages/httpx/_client.py", line 991, in _send_handling_redirects response = self._send_single_request(request) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/site-packages/httpx/_client.py", line 1027, in _send_single_request response = transport.handle_request(request) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/site-packages/httpx/_transports/default.py", line 236, in handle_request resp = self._pool.handle_request(req) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/site-packages/httpcore/_sync/connection_pool.py", line 216, in handle_request raise exc from None File "/usr/local/lib/python3.11/site-packages/httpcore/_sync/connection_pool.py", line 196, in handle_request response = connection.handle_request( ^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/site-packages/httpcore/_sync/connection.py", line 99, in handle_request raise exc File "/usr/local/lib/python3.11/site-packages/httpcore/_sync/connection.py", line 76, in handle_request stream = self._connect(request) ^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/site-packages/httpcore/_sync/connection.py", line 122, in _connect stream = self._network_backend.connect_tcp(**kwargs) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/site-packages/httpcore/_backends/sync.py", line 206, in connect_tcp sock = socket.create_connection( ^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/socket.py", line 839, in create_connection for res in getaddrinfo(host, port, 0, SOCK_STREAM): ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/socket.py", line 974, in getaddrinfo for res in _socket.getaddrinfo(host, port, family, type, proto, flags): ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ UnicodeError: encoding with 'idna' codec failed (UnicodeError: label empty or too long)`

**Comment by danielorozco06** [comment]
Hi, We need to add this another env var too:
AWS_SESSION_TOKEN

![image](https://github.com/user-attachments/assets/ad11c3ac-efc3-472f-860b-7a1f76ba821b)


With this the tool works now

![image](https://github.com/user-attachments/assets/59eac7c2-2496-42c5-a662-9cd25971190d)
